"""Generate a conservative steady-MRF OpenFOAM case from exported CFD patches.

The case intentionally uses one continuous fluid mesh.  The matching rotor and
stationary RSI surfaces remain part of the geometry export for a future AMI
case, but are omitted from snappyHexMesh so they cannot become internal walls.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
import json
import math
import os
import shutil
from typing import TYPE_CHECKING, Mapping, Sequence

if TYPE_CHECKING:
    from core.blade_builder import CfdDomainDefinition
    from core.pump_design import CompletePumpDesign


OPENFOAM_TARGET = "OpenCFD OpenFOAM v2312 or newer"
CASE_FORMULATION = "steady incompressible RANS, single-region MRF"


@dataclass(frozen=True)
class CaseBounds:
    minimum_m: tuple[float, float, float]
    maximum_m: tuple[float, float, float]
    cells: tuple[int, int, int]
    base_cell_size_m: float
    location_in_mesh_m: tuple[float, float, float]
    rotor_zone_p1_m: tuple[float, float, float]
    rotor_zone_p2_m: tuple[float, float, float]
    rotor_zone_radius_m: float


def _foam_header(object_name: str, class_name: str = "dictionary") -> str:
    return f"""/*--------------------------------*- C++ -*----------------------------------*\\
| OpenFOAM case generated by Turbomachinery Studio                         |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    format      ascii;
    class       {class_name};
    object      {object_name};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

"""


def _write_text(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as stream:
        stream.write(content.rstrip() + "\n")


def _vector(values: Sequence[float]) -> str:
    return "(" + " ".join(f"{value:.9g}" for value in values) + ")"


def _case_bounds(
    design: "CompletePumpDesign",
    definition: "CfdDomainDefinition",
    geometry_bounds_mm: Sequence[float],
) -> CaseBounds:
    if len(geometry_bounds_mm) != 6:
        raise ValueError("CFD geometry bounds must contain xmin..zmax.")
    raw_min = [float(value) * 1.0e-3 for value in geometry_bounds_mm[:3]]
    raw_max = [float(value) * 1.0e-3 for value in geometry_bounds_mm[3:]]
    extents = [upper - lower for lower, upper in zip(raw_min, raw_max)]
    if any(extent <= 0.0 for extent in extents):
        raise ValueError("CFD geometry bounds must have positive extents.")

    d2_m = design.impeller.outlet_diameter_d2 * 1.0e-3
    base_size = max(0.006, min(0.025, d2_m / 10.0))
    margin = max(2.0 * base_size, 0.08 * max(extents))
    lower = tuple(value - margin for value in raw_min)
    upper = tuple(value + margin for value in raw_max)
    padded_extents = [hi - lo for lo, hi in zip(lower, upper)]
    cells = tuple(
        max(8, min(80, int(math.ceil(extent / base_size))))
        for extent in padded_extents
    )

    inlet_outer = 0.5 * design.impeller.suction_diameter_ds * 1.0e-3
    inlet_inner = 0.5 * design.impeller.hub_diameter_dh * 1.0e-3
    inlet_sample_radius = 0.5 * (inlet_outer + inlet_inner)
    inlet_plane_z = definition.inlet_plane_z_mm * 1.0e-3
    inlet_length = definition.inlet_extension_length_mm * 1.0e-3
    location = (
        inlet_sample_radius,
        0.0,
        inlet_plane_z - 0.35 * inlet_length,
    )

    rotor_z_min = design.impeller.back_shroud_thickness * 1.0e-3
    rotor_z_max = (
        design.impeller.back_shroud_thickness + design.meridional.axial_length
    ) * 1.0e-3
    axial_pad = 0.25 * base_size
    rotor_radius = max(
        1.0e-6,
        definition.rsi_radius_mm * 1.0e-3 - 0.15 * base_size,
    )
    return CaseBounds(
        minimum_m=lower,
        maximum_m=upper,
        cells=cells,
        base_cell_size_m=base_size,
        location_in_mesh_m=location,
        rotor_zone_p1_m=(0.0, 0.0, rotor_z_min - axial_pad),
        rotor_zone_p2_m=(0.0, 0.0, rotor_z_max + axial_pad),
        rotor_zone_radius_m=rotor_radius,
    )


def _block_mesh_dict(bounds: CaseBounds) -> str:
    x0, y0, z0 = bounds.minimum_m
    x1, y1, z1 = bounds.maximum_m
    nx, ny, nz = bounds.cells
    return _foam_header("blockMeshDict") + f"""convertToMeters 1;

vertices
(
    ({x0:.9g} {y0:.9g} {z0:.9g})
    ({x1:.9g} {y0:.9g} {z0:.9g})
    ({x1:.9g} {y1:.9g} {z0:.9g})
    ({x0:.9g} {y1:.9g} {z0:.9g})
    ({x0:.9g} {y0:.9g} {z1:.9g})
    ({x1:.9g} {y0:.9g} {z1:.9g})
    ({x1:.9g} {y1:.9g} {z1:.9g})
    ({x0:.9g} {y1:.9g} {z1:.9g})
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)
);

edges ();
boundary
(
    background
    {{
        type patch;
        faces
        (
            (0 4 7 3) (1 2 6 5) (0 1 5 4)
            (3 7 6 2) (0 3 2 1) (4 5 6 7)
        );
    }}
);
mergePatchPairs ();
"""


def _feature_extract_dict(surface_names: Sequence[str]) -> str:
    entries = []
    for name in surface_names:
        entries.append(
            f"""{name}.stl
{{
    extractionMethod extractFromSurface;
    extractFromSurfaceCoeffs
    {{
        includedAngle 150;
    }}
    writeObj no;
}}"""
        )
    return _foam_header("surfaceFeatureExtractDict") + "\n\n".join(entries)


def _snappy_dict(bounds: CaseBounds, surface_names: Sequence[str]) -> str:
    geometry = []
    refinement = []
    features = []
    patch_types = {
        "rotor_inlet": "patch",
        "stationary_outlet": "patch",
        "rotor_walls": "wall",
        "virtual_inlet_walls": "wall",
        "stationary_walls": "wall",
    }
    for name in surface_names:
        geometry.append(f"    {name}.stl {{ type triSurfaceMesh; name {name}; }}")
        level = "(2 3)" if name.endswith("walls") else "(1 2)"
        refinement.append(
            f"""        {name}
        {{
            level {level};
            patchInfo {{ type {patch_types[name]}; }}
        }}"""
        )
        features.append(f'        {{ file "{name}.eMesh"; level 2; }}')
    return _foam_header("snappyHexMeshDict") + f"""castellatedMesh true;
snap            true;
addLayers       false;

geometry
{{
{chr(10).join(geometry)}
}}

castellatedMeshControls
{{
    maxLocalCells       800000;
    maxGlobalCells      1200000;
    minRefinementCells  0;
    maxLoadUnbalance    0.10;
    nCellsBetweenLevels 3;
    features
    (
{chr(10).join(features)}
    );
    refinementSurfaces
    {{
{chr(10).join(refinement)}
    }}
    resolveFeatureAngle 30;
    refinementRegions {{}}
    locationInMesh {_vector(bounds.location_in_mesh_m)};
    allowFreeStandingZoneFaces false;
}}

snapControls
{{
    nSmoothPatch 5;
    tolerance 2.0;
    nSolveIter 100;
    nRelaxIter 8;
    nFeatureSnapIter 10;
    implicitFeatureSnap false;
    explicitFeatureSnap true;
    multiRegionFeatureSnap false;
}}

addLayerControls
{{
    relativeSizes true;
    layers {{}}
    expansionRatio 1.2;
    finalLayerThickness 0.3;
    minThickness 0.1;
    nGrow 0;
    featureAngle 60;
    nRelaxIter 5;
    nSmoothSurfaceNormals 1;
    nSmoothNormals 3;
    nSmoothThickness 10;
    maxFaceThicknessRatio 0.5;
    maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle 90;
    nBufferCellsNoExtrude 0;
    nLayerIter 50;
}}

meshQualityControls
{{
    #include "meshQualityDict"
}}

mergeTolerance 1e-6;
"""


def _topo_set_dict(bounds: CaseBounds) -> str:
    return _foam_header("topoSetDict") + f"""actions
(
    {{
        name rotorCells;
        type cellSet;
        action new;
        source cylinderToCell;
        p1 {_vector(bounds.rotor_zone_p1_m)};
        p2 {_vector(bounds.rotor_zone_p2_m)};
        radius {bounds.rotor_zone_radius_m:.9g};
    }}
    {{
        name rotorZone;
        type cellZoneSet;
        action new;
        source setToCellZone;
        set rotorCells;
    }}
);
"""


def _field_file(
    name: str,
    field_class: str,
    dimensions: str,
    internal: str,
    boundaries: str,
) -> str:
    return (
        _foam_header(name, field_class)
        + f"dimensions      {dimensions};\n\n"
        + f"internalField   uniform {internal};\n\n"
        + "boundaryField\n{\n"
        + boundaries.rstrip()
        + "\n}\n"
    )


def _fields(design: "CompletePumpDesign") -> dict[str, str]:
    q = design.requirements.discharge_m3_h / 3600.0
    ds = design.impeller.suction_diameter_ds * 1.0e-3
    dh = design.impeller.hub_diameter_dh * 1.0e-3
    inlet_area = math.pi * 0.25 * (ds * ds - dh * dh)
    inlet_speed = q / inlet_area
    intensity = 0.05
    k = 1.5 * (intensity * inlet_speed) ** 2
    length_scale = max(1.0e-5, 0.07 * (ds - dh))
    omega_t = math.sqrt(k) / (0.09 ** 0.25 * length_scale)
    omega_rot = 2.0 * math.pi * design.requirements.rpm / 60.0

    u_boundary = f"""    rotor_inlet
    {{
        type flowRateInletVelocity;
        volumetricFlowRate constant {q:.9g};
        extrapolateProfile no;
        value uniform (0 0 {-inlet_speed:.9g});
    }}
    stationary_outlet {{ type zeroGradient; }}
    rotor_walls
    {{
        type rotatingWallVelocity;
        origin (0 0 0);
        axis (0 0 1);
        omega constant {omega_rot:.9g};
        value uniform (0 0 0);
    }}
    virtual_inlet_walls {{ type slip; }}
    stationary_walls {{ type noSlip; }}"""
    p_boundary = """    rotor_inlet { type zeroGradient; }
    stationary_outlet { type fixedValue; value uniform 0; }
    rotor_walls { type zeroGradient; }
    virtual_inlet_walls { type zeroGradient; }
    stationary_walls { type zeroGradient; }"""
    k_boundary = f"""    rotor_inlet {{ type fixedValue; value uniform {k:.9g}; }}
    stationary_outlet {{ type inletOutlet; inletValue uniform {k:.9g}; value uniform {k:.9g}; }}
    rotor_walls {{ type kqRWallFunction; value uniform {k:.9g}; }}
    virtual_inlet_walls {{ type zeroGradient; }}
    stationary_walls {{ type kqRWallFunction; value uniform {k:.9g}; }}"""
    omega_boundary = f"""    rotor_inlet {{ type fixedValue; value uniform {omega_t:.9g}; }}
    stationary_outlet
    {{
        type inletOutlet;
        inletValue uniform {omega_t:.9g};
        value uniform {omega_t:.9g};
    }}
    rotor_walls {{ type omegaWallFunction; value uniform {omega_t:.9g}; }}
    virtual_inlet_walls {{ type zeroGradient; }}
    stationary_walls {{ type omegaWallFunction; value uniform {omega_t:.9g}; }}"""
    nut_boundary = """    rotor_inlet { type calculated; value uniform 0; }
    stationary_outlet { type calculated; value uniform 0; }
    rotor_walls { type nutkWallFunction; value uniform 0; }
    virtual_inlet_walls { type calculated; value uniform 0; }
    stationary_walls { type nutkWallFunction; value uniform 0; }"""
    return {
        "U": _field_file("U", "volVectorField", "[0 1 -1 0 0 0 0]", "(0 0 0)", u_boundary),
        "p": _field_file("p", "volScalarField", "[0 2 -2 0 0 0 0]", "0", p_boundary),
        "k": _field_file("k", "volScalarField", "[0 2 -2 0 0 0 0]", f"{k:.9g}", k_boundary),
        "omega": _field_file(
            "omega",
            "volScalarField",
            "[0 0 -1 0 0 0 0]",
            f"{omega_t:.9g}",
            omega_boundary,
        ),
        "nut": _field_file("nut", "volScalarField", "[0 2 -1 0 0 0 0]", "0", nut_boundary),
    }


def _constant_files(design: "CompletePumpDesign") -> dict[str, str]:
    nu = design.fluid.kinematic_viscosity
    omega_rot = 2.0 * math.pi * design.requirements.rpm / 60.0
    transport = _foam_header("transportProperties") + f"""transportModel Newtonian;
nu              [0 2 -1 0 0 0 0] {nu:.9g};
"""
    turbulence = _foam_header("turbulenceProperties") + """simulationType RAS;

RAS
{
    RASModel        kOmegaSST;
    turbulence      on;
    printCoeffs     on;
}
"""
    mrf = _foam_header("MRFProperties") + f"""rotor
{{
    active              yes;
    cellZone            rotorZone;
    nonRotatingPatches  (rotor_inlet virtual_inlet_walls stationary_outlet stationary_walls);
    origin              (0 0 0);
    axis                (0 0 1);
    omega               {omega_rot:.9g};
}}
"""
    return {
        "transportProperties": transport,
        "turbulenceProperties": turbulence,
        "MRFProperties": mrf,
    }


def _system_files(design: "CompletePumpDesign", bounds: CaseBounds) -> dict[str, str]:
    density = design.fluid.density
    control = _foam_header("controlDict") + f"""application     simpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         3000;
deltaT          1;
writeControl    timeStep;
writeInterval   250;
purgeWrite      3;
writeFormat     binary;
writePrecision  8;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable true;

functions
{{
    totalPressure
    {{
        type            pressure;
        libs            (fieldFunctionObjects);
        mode            total;
        p               p;
        U               U;
        rho             rhoInf;
        rhoInf          {density:.9g};
        result          pTotal;
        executeControl  timeStep;
        executeInterval 1;
        writeControl    timeStep;
        writeInterval   10;
    }}

    inletTotalPressure
    {{
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        fields          (pTotal);
        operation       areaAverage;
        regionType      patch;
        name            rotor_inlet;
        writeControl    timeStep;
        writeInterval   10;
    }}

    outletTotalPressure
    {{
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        fields          (pTotal);
        operation       areaAverage;
        regionType      patch;
        name            stationary_outlet;
        writeControl    timeStep;
        writeInterval   10;
    }}

    inletFlow
    {{
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        fields          (phi);
        operation       sum;
        regionType      patch;
        name            rotor_inlet;
        writeControl    timeStep;
        writeInterval   10;
    }}

    outletFlow
    {{
        type            surfaceFieldValue;
        libs            (fieldFunctionObjects);
        fields          (phi);
        operation       sum;
        regionType      patch;
        name            stationary_outlet;
        writeControl    timeStep;
        writeInterval   10;
    }}

    rotorForces
    {{
        type            forces;
        libs            ("libforces.so");
        patches         (rotor_walls);
        rho             rhoInf;
        rhoInf          {density:.9g};
        pRef            0;
        CofR            (0 0 0);
        writeControl    timeStep;
        writeInterval   10;
    }}

    convergenceHistory
    {{
        type            solverInfo;
        libs            ("libutilityFunctionObjects.so");
        fields          (U p k omega);
        writeResidualFields no;
        writeControl    timeStep;
        writeInterval   10;
    }}
}}
"""
    schemes = _foam_header("fvSchemes") + """ddtSchemes { default steadyState; }
gradSchemes { default cellLimited Gauss linear 1; }
divSchemes
{
    default none;
    div(phi,U) bounded Gauss linearUpwind grad(U);
    div(phi,k) bounded Gauss upwind;
    div(phi,omega) bounded Gauss upwind;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes { default Gauss linear limited 0.5; }
interpolationSchemes { default linear; }
snGradSchemes { default limited 0.5; }
wallDist { method meshWave; }
"""
    solution = _foam_header("fvSolution") + """solvers
{
    p
    {
        solver GAMG;
        tolerance 1e-8;
        relTol 0.05;
        smoother GaussSeidel;
    }
    "(U|k|omega)"
    {
        solver smoothSolver;
        smoother symGaussSeidel;
        tolerance 1e-7;
        relTol 0.1;
    }
}

SIMPLE
{
    nNonOrthogonalCorrectors 1;
    consistent yes;
    residualControl
    {
        p 1e-5;
        U 1e-5;
        k 1e-5;
        omega 1e-5;
    }
}

relaxationFactors
{
    fields { p 0.3; }
    equations
    {
        U 0.7;
        k 0.7;
        omega 0.7;
    }
}
"""
    decompose = _foam_header("decomposeParDict") + """numberOfSubdomains 4;
method scotch;
"""
    mesh_quality = _foam_header("meshQualityDict") + """maxNonOrtho 70;
maxBoundarySkewness 20;
maxInternalSkewness 4;
maxConcave 80;
minVol 1e-15;
minTetQuality 1e-30;
minArea -1;
minTwist 0.02;
minDeterminant 0.001;
minFaceWeight 0.02;
minVolRatio 0.01;
minTriangleTwist -1;
nSmoothScale 4;
errorReduction 0.75;
relaxed { maxNonOrtho 75; }
"""
    return {
        "controlDict": control,
        "fvSchemes": schemes,
        "fvSolution": solution,
        "decomposeParDict": decompose,
        "meshQualityDict": mesh_quality,
        "blockMeshDict": _block_mesh_dict(bounds),
        "topoSetDict": _topo_set_dict(bounds),
    }


def generate_steady_mrf_case(
    design: "CompletePumpDesign",
    definition: "CfdDomainDefinition",
    case_dir: str,
    boundary_stls: Mapping[str, str],
    geometry_bounds_mm: Sequence[float],
) -> dict:
    """Write a complete first-pass MRF case and return its manifest."""

    required = {
        "rotor_inlet",
        "rotor_walls",
        "virtual_inlet_walls",
        "stationary_outlet",
        "stationary_walls",
    }
    missing = sorted(required.difference(boundary_stls))
    if missing:
        raise ValueError("Steady MRF case is missing CFD patches: " + ", ".join(missing))
    if not design.architecture or not design.architecture.has_complete_assembly_cad:
        raise ValueError(
            "Steady MRF case generation currently requires the complete "
            "single-stage volute architecture."
        )
    failed = [check for check in design.engineering_record.checks if check.status == "fail"]
    if failed:
        raise ValueError("Steady MRF case blocked by engineering check: " + failed[0].message)
    for name in required:
        if not os.path.isfile(boundary_stls[name]):
            raise FileNotFoundError(boundary_stls[name])

    bounds = _case_bounds(design, definition, geometry_bounds_mm)
    tri_surface_dir = os.path.join(case_dir, "constant", "triSurface")
    os.makedirs(tri_surface_dir, exist_ok=True)
    surface_names = sorted(required)
    for name in surface_names:
        shutil.copyfile(boundary_stls[name], os.path.join(tri_surface_dir, f"{name}.stl"))

    for name, content in _fields(design).items():
        _write_text(os.path.join(case_dir, "0", name), content)
    for name, content in _constant_files(design).items():
        _write_text(os.path.join(case_dir, "constant", name), content)
    system_files = _system_files(design, bounds)
    system_files["surfaceFeatureExtractDict"] = _feature_extract_dict(surface_names)
    system_files["snappyHexMeshDict"] = _snappy_dict(bounds, surface_names)
    for name, content in system_files.items():
        _write_text(os.path.join(case_dir, "system", name), content)

    allrun = """#!/bin/sh
cd "${0%/*}" || exit 1
: "${WM_PROJECT_DIR:?Source an OpenCFD OpenFOAM environment before running this case.}"
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"
runApplication surfaceFeatureExtract
runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication checkMesh -allGeometry -allTopology
runApplication topoSet
runApplication checkMesh -allGeometry -allTopology
runApplication simpleFoam
"""
    allclean = """#!/bin/sh
cd "${0%/*}" || exit 1
: "${WM_PROJECT_DIR:?Source an OpenCFD OpenFOAM environment before cleaning this case.}"
. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"
cleanCase
rm -f constant/triSurface/*.eMesh constant/triSurface/*.obj
"""
    _write_text(os.path.join(case_dir, "Allrun"), allrun)
    _write_text(os.path.join(case_dir, "Allclean"), allclean)

    q = design.requirements.discharge_m3_h / 3600.0
    manifest = {
        "schema_version": 1,
        "design_id": design.design_id,
        "target": OPENFOAM_TARGET,
        "formulation": CASE_FORMULATION,
        "solver": "simpleFoam",
        "turbulence_model": "kOmegaSST",
        "operating_point": {
            "flow_m3_s": q,
            "target_head_m": design.requirements.head_m,
            "rpm": design.requirements.rpm,
            "omega_rad_s": 2.0 * math.pi * design.requirements.rpm / 60.0,
            "kinematic_viscosity_m2_s": design.fluid.kinematic_viscosity,
            "density_kg_m3": design.fluid.density,
        },
        "mesh": asdict(bounds),
        "external_boundaries": surface_names,
        "excluded_internal_surfaces": ["rotor_rsi", "stationary_rsi"],
        "rotating_cell_zone": "rotorZone",
        "preflight": {
            "complete_single_stage_volute_domain": True,
            "engineering_failures": 0,
            "stl_coordinate_unit": "m",
        },
        "limitations": [
            "This is a steady MRF screening case, not a transient blade-passing simulation.",
            "Boundary layers are disabled in the first automatic mesh; perform "
            "a y+ study before design decisions.",
            "Leakage, seal, balance-hole, and secondary shroud-side flow paths are omitted.",
            "Run checkMesh and establish mesh independence before accepting hydraulic results.",
        ],
        "manual_basis": [
            "CFturbo_en.pdf p. 595-600: rotor-stator virtual geometry and RSI workflow",
            "CFturbo_en.pdf p. 695: outlet extension normal to diffuser outlet",
            "CFturbo_en.pdf p. 696: RSI parts included in volute virtual geometry",
        ],
    }
    manifest_path = os.path.join(case_dir, "case_manifest.json")
    _write_text(manifest_path, json.dumps(manifest, indent=2))
    readme = f"""# Generated steady-MRF pump case

Target: {OPENFOAM_TARGET}

This is the first automated CFD screening case for design `{design.design_id}`.
The mesh is a single continuous fluid region. `rotor_rsi.stl` and
`stationary_rsi.stl` are intentionally not copied into this case because an MRF
model does not need a coupled internal interface.

Run on Linux/WSL after sourcing OpenFOAM:

```sh
chmod +x Allrun Allclean
./Allrun
```

Do not use the result for release decisions until `checkMesh` passes, mass-flow
closure is confirmed, and mesh/y+ independence has been demonstrated. The
future transient phase will use the exported matched RSI surfaces as an AMI.
"""
    _write_text(os.path.join(case_dir, "README.md"), readme)
    return {**manifest, "case_directory": case_dir, "manifest_path": manifest_path}
